# 7 - Model selection
In this notebook we compare several models for the dependence of the portfolio standard deviation on volatility, leverage, and time horizon.

### Fixed time horizon
We first focus on a fixed time horizon and consider the following models:
- `quadratic`: quadratic in all features (6 parameters)
- `log_quadratic`: quadratic in all features, target variable transformed by `log(1 + y)` (6 parameters)
- `cubic`: cubic in all features (10 parameters)
- `log_cubic`: cubic in all features, target variable transformed by `log(1 + y)` (10 parameters)
- `quartic`: quartic in all features (15 parameters)
- `log_quartic`: quartic in all features, target variable transformed by `log(1 + y)` (15 parameters)
- `split_quartic`: $y = a L\sigma + b L^2 \sigma + c L \sigma^2 + d L^2 \sigma^2$ (4 parameters)
- `log_split_quartic`: $\log(1 + y) = a L\sigma + b L^2 \sigma + c L \sigma^2 + d L^2 \sigma^2$ (4 parameters)
- `lasso_***`: lasso versions of all previous models
- `theoretical`: see below (1 parameter)
- `log_theoretical`: same as `theoretical`, target variable transformed by `log(1 + y)` (1 parameter)

##### The theoretical model
From the preliminary model exploration, the portfolio standard deviation seems to be quadratic in leverage and volatility, at least for small leverages and volatility, and for short time horizons.  More precisely, relation looks linear in volatility once leverage is fixed, and linear in leverage once volatility is fixed.  Because when leverage is 1 or when volatility is 0 the two portfolio are exactly the same, we conclude that a reasonable model for the standard deviation of the leveraged portfolio at a fixed time horizon is
$$
\sigma_{\text{lev},d} = a_d \sigma (L - 1),
$$
where $\sigma_{\text{lev}, d}$ is the volatility of the portfolio after $d$ days, $a_d$ is a constant (to be figured out) depending on the number of days $d$ the portfolio is held, $\sigma$ is the underlying stock annual volatility, and $L$ is the leverage factor.

In [1]:
import pandas as pd
from sklearn.metrics import mean_squared_error as mse

from models import generate_model, theoretical_model_fixed

In [2]:
# load train with horizon=5
train = []
for i in range(1, 11):
    t = pd.read_csv(f"output/train/df_train_{i}.csv", index_col=0)
    t = t[t.horizon == 5]
    t.drop(columns=["horizon"], inplace=True)
    train.append(t)

# load test with horizon=5
test = []
for i in range(1, 6):
    t = pd.read_csv(f"output/test/df_test_{i}.csv", index_col=0)
    t = t[t.horizon == 5]
    t.drop(columns=["horizon"], inplace=True)
    test.append(t)

In [3]:
train[0]

        leverage     sigma          mean       std
4           1.01  0.010000  6.882650e-08  0.000014
14          1.01  0.012965 -2.482670e-07  0.000018
24          1.01  0.015930  1.946996e-07  0.000022
34          1.01  0.018894  2.624057e-07  0.000026
44          1.01  0.021859  1.844182e-07  0.000031
...          ...       ...           ...       ...
339954      3.00  0.588141 -2.633804e-03  0.171084
339964      3.00  0.591106 -7.600245e-05  0.172755
339974      3.00  0.594070 -9.808169e-05  0.170017
339984      3.00  0.597035  2.473307e-03  0.169677
339994      3.00  0.600000  9.019926e-04  0.172924

[34000 rows x 4 columns]

In [4]:
model = {
    "quadratic": generate_model(degree=2),  # 6 parameters
    "log_quadratic": generate_model(degree=2, take_log=True),  # 6 parameters
    "cubic": generate_model(degree=3),  # 10 parameters
    "log_cubic": generate_model(degree=3, take_log=True),  # 10 parameters
    "quartic": generate_model(degree=4),  # 15 parameters
    "log_quartic": generate_model(degree=4, take_log=True),  # 15 parameters
    "split_quartic": generate_model(degree=4, split_quartic=True),  # 4 parameters
    "log_split_quartic": generate_model(
        degree=4, split_quartic=True, take_log=True
    ),  # 4 parameters
    "lasso_quadratic": generate_model(degree=2, lasso=0.5),  # 6 parameters
    "lasso_log_quadratic": generate_model(
        degree=2, take_log=True, lasso=0.5
    ),  # 6 parameters
    "lasso_cubic": generate_model(degree=3, lasso=0.5),  # 10 parameters
    "lasso_log_cubic": generate_model(
        degree=3, take_log=True, lasso=0.5
    ),  # 10 parameters
    "lasso_quartic": generate_model(degree=4, lasso=0.5),  # 15 parameters
    "lasso_log_quartic": generate_model(
        degree=4, take_log=True, lasso=0.5
    ),  # 15 parameters
    "lasso_split_quartic": generate_model(
        degree=4, split_quartic=True, lasso=0.5
    ),  # 4 parameters
    "lasso_log_split_quartic": generate_model(
        degree=4, split_quartic=True, take_log=True, lasso=0.5
    ),  # 4 parameters
    "theoretical": theoretical_model_fixed(),  # 1 parameter
    "log_theoretical": theoretical_model_fixed(take_log=True),  # 1 parameter
}

In [5]:
results_list = []

for pipe_id, pipe in model.items():
    for train_id, tr_set in enumerate(train):
        pipe.fit(tr_set[["leverage", "sigma"]], tr_set["std"])

        for test_id, test_set in enumerate(test):
            pred = pipe.predict(test_set[["leverage", "sigma"]])

            results_list.append(
                {
                    "model": pipe_id,
                    "train": train_id,
                    "test": test_id,
                    "mse": mse(test_set["std"], pred),
                    "R2": pipe.score(test_set[["leverage", "sigma"]], test_set["std"]),
                }
            )

results = pd.DataFrame(results_list)

In [6]:
results

               model  train  test           mse        R2
0          quadratic      0     0  2.399099e-07  0.999834
1          quadratic      0     1  2.342504e-07  0.999838
2          quadratic      0     2  2.403801e-07  0.999835
3          quadratic      0     3  2.375981e-07  0.999835
4          quadratic      0     4  2.395686e-07  0.999833
..               ...    ...   ...           ...       ...
895  log_theoretical      9     0  7.556830e-07  0.999477
896  log_theoretical      9     1  7.593297e-07  0.999474
897  log_theoretical      9     2  7.371180e-07  0.999493
898  log_theoretical      9     3  7.385531e-07  0.999486
899  log_theoretical      9     4  7.362245e-07  0.999488

[900 rows x 5 columns]

In [7]:
mean_result = results.groupby("model")[["mse", "R2"]].mean()
std_result = results.groupby("model")[["mse", "R2"]].std()

In [8]:
mean_result

                                  mse        R2
model
cubic                    2.175478e-07  0.999849
lasso_cubic              3.338431e-03 -1.313303
lasso_log_cubic          3.338431e-03 -1.313303
lasso_log_quadratic      3.338431e-03 -1.313303
lasso_log_quartic        3.338431e-03 -1.313303
lasso_log_split_quartic  3.338431e-03 -1.313303
lasso_quadratic          3.338431e-03 -1.313303
lasso_quartic            3.338431e-03 -1.313303
lasso_split_quartic      3.338431e-03 -1.313303
log_cubic                2.183443e-07  0.999849
log_quadratic            2.990830e-07  0.999793
log_quartic              2.161288e-07  0.999850
log_split_quartic        1.727708e-05  0.988029
log_theoretical          7.456290e-07  0.999483
quadratic                2.383710e-07  0.999835
quartic                  2.161134e-07  0.999850
split_quartic            1.491540e-05  0.989665
theoretical              3.100714e-07  0.999785

In [9]:
std_result

                                  mse        R2
model
cubic                    1.335931e-09  0.000001
lasso_cubic              5.918397e-06  0.005290
lasso_log_cubic          5.918397e-06  0.005290
lasso_log_quadratic      5.918397e-06  0.005290
lasso_log_quartic        5.918397e-06  0.005290
lasso_log_split_quartic  5.918397e-06  0.005290
lasso_quadratic          5.918397e-06  0.005290
lasso_quartic            5.918397e-06  0.005290
lasso_split_quartic      5.918397e-06  0.005290
log_cubic                1.580082e-09  0.000001
log_quadratic            3.836927e-09  0.000003
log_quartic              1.402904e-09  0.000001
log_split_quartic        3.162033e-07  0.000174
log_theoretical          1.012730e-08  0.000007
quadratic                2.312269e-09  0.000002
quartic                  1.405799e-09  0.000001
split_quartic            2.762853e-07  0.000153
theoretical              5.476444e-09  0.000004

Best models: `quartic` > `cubic` > `quadratic` > `theoretical` (with `log_` version worse). We choose `theoretical` because it is the simplest best performing model.

### Dependence on time horizon
Suppose we change the time horizon from $d=1$ to $d=D$ days. This has two effects:
- the number of updates of the leveraged ETF is multiplied by $D$, and
- the total volatility during the period of time is (assuming GBM, at least) multiplied by $\sqrt{D}$.

This can be equivalently seen as holding the portfolio for 1 day, rebalancing it $D$ times, with an equivalent volatility of $\sqrt{D} \sigma$.  Moreover, if the volatility and $D$ are sufficiently small, the continuous approximation of the leveraged portfolio discussed in Notebook 02 is a good approximation of the discrete-time rebalancing, so the increased frequency of rebalancing has a negligible effect on the portfolio dynamic.  The only effect left is then that $\sigma$ is replaced by $\sqrt{D} \sigma$.  Hence, a reasonable model for the leveraged portfolio volatility after $d$ days is 
$$
\sigma_\text{lev} = a \sqrt{d} \sigma (L - 1),
$$
where $a$ is the only parameter left to find.

#### Models
We consider two models:
- In the first, $d$ is a categorical one-hot-encoded variable and the model is given by the fixed-horizon theoretical model. This is equivalent to training $\sigma_\text{lev} = a_d \sigma (L - 1)$ for each fixed $d$. We call this `theoretical_onehot`.
- In the second, $d$ is a numerical feature, and we assume that the dependence is $\sigma_\text{lev} = a \sqrt{d} \sigma (L - 1)$. We call this `theoretical_variable`.

In [10]:
train_var = [
    pd.read_csv(f"output/train/df_train_{i}.csv", index_col=0) for i in range(1, 11)
]
test_var = [
    pd.read_csv(f"output/test/df_test_{i}.csv", index_col=0) for i in range(1, 6)
]

In [11]:
from models import theoretical_model_onehot, theoretical_model_variable

model_var = {
    "theoretical_onehot": theoretical_model_onehot(),
    "theoretical_variable": theoretical_model_variable(),
}

In [12]:
results_var_list = []

for pipe_id, pipe in model_var.items():
    for train_id, tr_set in enumerate(train_var):
        pipe.fit(tr_set[["leverage", "sigma", "horizon"]], tr_set["std"])

        for test_id, test_set in enumerate(test_var):
            pred = pipe.predict(test_set[["leverage", "sigma", "horizon"]])

            results_var_list.append(
                {
                    "model": pipe_id,
                    "train": train_id,
                    "test": test_id,
                    "mse": mse(test_set["std"], pred),
                    "R2": pipe.score(
                        test_set[["leverage", "sigma", "horizon"]], test_set["std"]
                    ),
                }
            )

results_var = pd.DataFrame(results_var_list)

In [13]:
mean_result_var = results_var.groupby("model")[["mse", "R2"]].mean()
std_result_var = results_var.groupby("model")[["mse", "R2"]].std()

In [14]:
mean_result_var

                           mse        R2
model
theoretical_onehot    0.000194  0.891370
theoretical_variable  0.000153  0.914181

In [15]:
std_result_var

                               mse        R2
model
theoretical_onehot    6.001525e-07  0.000065
theoretical_variable  3.039029e-07  0.000149

The `theoretical_variable` model has better $R^2$ and mean-squared-error (indicating that `theoretical_onehot` is probably overfitting), and is thus our model-of-choice.