# Model selection
From the preliminary model exploration, the portfolio standard deviation seems to be quadratic in leverage and volatility, at least for small leverages and volatility, and for short time horizons.  More precisely, relation looks linear in volatility once leverage is fixed, and linear in leverage once volatility is fixed.  Because when leverage is 1 or when volatility is 0 the two portfolio are exactly the same, we conclude that a reasonable model for the standard deviation of the leveraged portfolio at a fixed time horizon is
$$
\sigma_{\text{lev},d} = a_d \sigma (L - 1),
$$
where $\sigma_{\text{lev}, d}$ is the volatility of the portfolio after $d$ days, $a_d$ is a constant (to be figured out) depending on the number of days $d$ the portfolio is held, $\sigma$ is the underlying stock annual volatility, and $L$ is the leverage factor.

In [1]:
import pandas as pd
from sklearn.metrics import mean_squared_error as mse

from models import generate_model, theoretical_model

In [2]:
# load train with duration=5
train = []
for i in range(1, 11):
    t = pd.read_csv(f"output/train/df_train_{i}.csv", index_col=0)
    t = t[t.duration == 5]
    t.drop(columns=["duration"], inplace=True)
    train.append(t)

# load test with duration=5
test = []
for i in range(1, 6):
    t = pd.read_csv(f"output/test/df_test_{i}.csv", index_col=0)
    t = t[t.duration == 5]
    t.drop(columns=["duration"], inplace=True)
    test.append(t)

In [3]:
train[0]

        leverage     sigma          mean       std
4           1.01  0.010000 -1.317380e-07  0.000014
14          1.01  0.012965 -2.078609e-07  0.000018
24          1.01  0.015930 -3.436753e-07  0.000022
34          1.01  0.018894  2.613153e-07  0.000027
44          1.01  0.021859 -3.431489e-07  0.000031
...          ...       ...           ...       ...
339954      3.00  0.588141  1.036702e-04  0.170414
339964      3.00  0.591106  1.195788e-03  0.171991
339974      3.00  0.594070  2.814508e-05  0.170791
339984      3.00  0.597035  1.865284e-03  0.171263
339994      3.00  0.600000 -1.925190e-03  0.173556

[34000 rows x 4 columns]

In [ ]:
model = {
    "quadratic": generate_model(degree=2),  # 6 parameters
    "log_quadratic": generate_model(degree=2, take_log=True),  # 6 parameters
    "cubic": generate_model(degree=3),  # 10 parameters
    "log_cubic": generate_model(degree=3, take_log=True),  # 10 parameters
    "quartic": generate_model(degree=4),  # 15 parameters
    "log_quartic": generate_model(degree=4, take_log=True),  # 15 parameters
    "split_quartic": generate_model(degree=4, split_quartic=True),  # 4 parameters
    "log_split_quartic": generate_model(
        degree=4, split_quartic=True, take_log=True
    ),  # 4 parameters
    "lasso_quadratic": generate_model(degree=2, lasso=0.5),  # 6 parameters
    "lasso_log_quadratic": generate_model(
        degree=2, take_log=True, lasso=0.5
    ),  # 6 parameters
    "lasso_cubic": generate_model(degree=3, lasso=0.5),  # 10 parameters
    "lasso_log_cubic": generate_model(
        degree=3, take_log=True, lasso=0.5
    ),  # 10 parameters
    "lasso_quartic": generate_model(degree=4, lasso=0.5),  # 15 parameters
    "lasso_log_quartic": generate_model(
        degree=4, take_log=True, lasso=0.5
    ),  # 15 parameters
    "lasso_split_quartic": generate_model(
        degree=4, split_quartic=True, lasso=0.5
    ),  # 4 parameters
    "lasso_log_split_quartic": generate_model(
        degree=4, split_quartic=True, take_log=True, lasso=0.5
    ),  # 4 parameters
    "theoretical": theoretical_model_fixed(),  # 1 parameter
    "log_theoretical": theoretical_model_fixed(take_log=True),  # 1 parameter
}

In [5]:
results_list = []

for pipe_id, pipe in model.items():
    for train_id, tr_set in enumerate(train):
        pipe.fit(tr_set[["leverage", "sigma"]], tr_set["std"])

        for test_id, test_set in enumerate(test):
            pred = pipe.predict(test_set[["leverage", "sigma"]])

            results_list.append(
                {
                    "model": pipe_id,
                    "train": train_id,
                    "test": test_id,
                    "mse": mse(test_set["std"], pred),
                    "R2": pipe.score(test_set[["leverage", "sigma"]], test_set["std"]),
                }
            )

results = pd.DataFrame(results_list)

In [6]:
results

               model  train  test           mse        R2
0          quadratic      0     0  2.478707e-07  0.999829
1          quadratic      0     1  2.391096e-07  0.999834
2          quadratic      0     2  2.403452e-07  0.999835
3          quadratic      0     3  2.376347e-07  0.999835
4          quadratic      0     4  2.395569e-07  0.999833
..               ...    ...   ...           ...       ...
895  log_theoretical      9     0  7.344284e-07  0.999492
896  log_theoretical      9     1  7.270094e-07  0.999497
897  log_theoretical      9     2  7.386221e-07  0.999492
898  log_theoretical      9     3  7.398352e-07  0.999485
899  log_theoretical      9     4  7.374395e-07  0.999487

[900 rows x 5 columns]

In [7]:
mean_result = results.groupby("model")[["mse", "R2"]].mean()
std_result = results.groupby("model")[["mse", "R2"]].std()

In [8]:
mean_result

                                  mse        R2
model
cubic                    2.185106e-07  0.999849
lasso_cubic              3.339027e-03 -1.312945
lasso_log_cubic          3.339027e-03 -1.312945
lasso_log_quadratic      3.339027e-03 -1.312945
lasso_log_quartic        3.339027e-03 -1.312945
lasso_log_split_quartic  3.339027e-03 -1.312945
lasso_quadratic          3.339027e-03 -1.312945
lasso_quartic            3.339027e-03 -1.312945
lasso_split_quartic      3.339027e-03 -1.312945
log_cubic                2.189687e-07  0.999848
log_quadratic            2.966113e-07  0.999795
log_quartic              2.168615e-07  0.999850
log_split_quartic        1.725066e-05  0.988051
log_theoretical          7.348305e-07  0.999491
quadratic                2.409580e-07  0.999833
quartic                  2.168393e-07  0.999850
split_quartic            1.489231e-05  0.989685
theoretical              3.160381e-07  0.999781

In [9]:
std_result

                                  mse        R2
model
cubic                    3.566020e-09  0.000002
lasso_cubic              6.047382e-06  0.005375
lasso_log_cubic          6.047382e-06  0.005375
lasso_log_quadratic      6.047382e-06  0.005375
lasso_log_quartic        6.047382e-06  0.005375
lasso_log_split_quartic  6.047382e-06  0.005375
lasso_quadratic          6.047382e-06  0.005375
lasso_quartic            6.047382e-06  0.005375
lasso_split_quartic      6.047382e-06  0.005375
log_cubic                3.924616e-09  0.000003
log_quadratic            4.299968e-09  0.000003
log_quartic              3.739277e-09  0.000003
log_split_quartic        3.161929e-07  0.000177
log_theoretical          4.634961e-09  0.000004
quadratic                3.635172e-09  0.000002
quartic                  3.750797e-09  0.000003
split_quartic            2.760162e-07  0.000155
theoretical              5.629603e-09  0.000003

Best models: `quartic` > `cubic` > `quadratic` > `theoretical` (with `log_` version worse). We choose `theoretical` because it is the simplest best performing model.

### Dependence on time horizon
Suppose we change the time horizon from $d=1$ to $d=D$ days. This has two effects:
- the number of updates of the leveraged ETF is multiplied by $D$, and
- the total volatility during the period of time is (assuming GBM, at least) multiplied by $\sqrt{D}$.

This can be equivalently seen as holding the portfolio for 1 day, rebalancing it $D$ times, with an equivalent volatility of $\sqrt{D} \sigma$.  Moreover, if the volatility and $D$ are sufficiently small, the continuous approximation of the leveraged portfolio discussed in Notebook 02 is a good approximation of the discrete-time rebalancing, so the increased frequency of rebalancing has a negligible effect on the portfolio dynamic.  The only effect left is then that $\sigma$ is replaced by $\sqrt{D} \sigma$.  Hence, a reasonable model for the leveraged portfolio volatility after $d$ days is 
$$
\sigma_\text{lev} = a \sqrt{d} \sigma (L - 1),
$$
where $a$ is the only parameter left to find.