In [1]:
import pandas as pd
from sklearn.metrics import mean_squared_error as mse

from models import generate_model

In [2]:
model = {
    "quadratic": generate_model(degree=2),  # 6 parameters
    "log_quadratic": generate_model(degree=2, take_log=True),  # 6 parameters
    "cubic": generate_model(degree=3),  # 10 parameters
    "log_cubic": generate_model(degree=3, take_log=True),  # 10 parameters
    "quartic": generate_model(degree=4),  # 15 parameters
    "log_quartic": generate_model(degree=4, take_log=True),  # 15 parameters
    "split_quartic": generate_model(degree=4, split_quartic=True),  # 4 parameters
    "log_split_quartic": generate_model(
        degree=4, split_quartic=True, take_log=True
    ),  # 4 parameters
    "lasso_quadratic": generate_model(degree=2, lasso=0.5),  # 6 parameters
    "lasso_log_quadratic": generate_model(
        degree=2, take_log=True, lasso=0.5
    ),  # 6 parameters
    "lasso_cubic": generate_model(degree=3, lasso=0.5),  # 10 parameters
    "lasso_log_cubic": generate_model(
        degree=3, take_log=True, lasso=0.5
    ),  # 10 parameters
    "lasso_quartic": generate_model(degree=4, lasso=0.5),  # 15 parameters
    "lasso_log_quartic": generate_model(
        degree=4, take_log=True, lasso=0.5
    ),  # 15 parameters
    "lasso_split_quartic": generate_model(
        degree=4, split_quartic=True, lasso=0.5
    ),  # 4 parameters
    "lasso_log_split_quartic": generate_model(
        degree=4, split_quartic=True, take_log=True, lasso=0.5
    ),  # 4 parameters
}

train = [pd.read_csv(f"output/train/df_train_{i}.csv") for i in range(1, 11)]
test = [pd.read_csv(f"output/test/df_test_{i}.csv") for i in range(1, 6)]

In [3]:
results_list = []

for pipe_id, pipe in model.items():
    for train_id, tr_set in enumerate(train):
        pipe.fit(tr_set[["leverage", "sigma"]], tr_set["std"])

        for test_id, test_set in enumerate(test):
            pred = pipe.predict(test_set[["leverage", "sigma"]])

            results_list.append(
                {
                    "model": pipe_id,
                    "train": train_id,
                    "test": test_id,
                    "mse": mse(test_set["std"], pred),
                    "R2": pipe.score(test_set[["leverage", "sigma"]], test_set["std"]),
                }
            )

results = pd.DataFrame(results_list)

In [4]:
results

                       model  train  test        mse        R2
0                  quadratic      0     0   8.980838  0.728537
1                  quadratic      0     1   1.731688  0.076041
2                  quadratic      0     2   9.540021  0.714738
3                  quadratic      0     3  11.085495  0.681279
4                  quadratic      0     4  10.822972  0.690475
..                       ...    ...   ...        ...       ...
795  lasso_log_split_quartic      9     0  42.590441 -0.287378
796  lasso_log_split_quartic      9     1   2.887852 -0.540842
797  lasso_log_split_quartic      9     2  42.997365 -0.285691
798  lasso_log_split_quartic      9     3  44.236998 -0.271865
799  lasso_log_split_quartic      9     4  44.463662 -0.271611

[800 rows x 5 columns]

In [5]:
mean_result = results.groupby("model")[["mse", "R2"]].mean()
std_result = results.groupby("model")[["mse", "R2"]].std()

In [6]:
mean_result

                               mse        R2
model
cubic                     6.768927  0.773581
lasso_cubic              20.606374 -0.492615
lasso_log_cubic          32.661174 -0.228319
lasso_log_quadratic      32.932538 -0.242843
lasso_log_quartic        32.510667 -0.228083
lasso_log_split_quartic  32.510666 -0.228083
lasso_quadratic          22.756881 -0.557178
lasso_quartic            18.174919 -0.413682
lasso_split_quartic      18.162703 -0.414930
log_cubic                 6.767667  0.792589
log_quadratic             6.192188  0.809483
log_quartic               6.228518  0.808819
log_split_quartic         7.740729  0.761722
quadratic                 9.329746  0.587813
quartic                   6.192186  0.808206
split_quartic             7.415520  0.742910

In [7]:
std_result

                               mse        R2
model
cubic                     3.474146  0.054625
lasso_cubic               6.979110  1.843879
lasso_log_cubic          15.242235  0.112809
lasso_log_quadratic      15.331641  0.118955
lasso_log_quartic        15.155251  0.122975
lasso_log_split_quartic  15.155251  0.122975
lasso_quadratic           7.807860  1.808676
lasso_quartic             5.400471  1.861561
lasso_split_quartic       5.376171  1.865562
log_cubic                 3.744291  0.092691
log_quadratic             3.173476  0.074151
log_quartic               3.201199  0.075658
log_split_quartic         4.316919  0.106034
quadratic                 4.651562  0.227700
quartic                   3.175777  0.071706
split_quartic             3.983867  0.066424

The `log_quadratic` model has second-best `mse` and `R2`, and lowest standard deviation of `mse` among train-test couples.